name: üêç Gerar anima√ß√£o da cobrinha azul

on:
  schedule:
    - cron: "1 0 * * *"  # Atualiza todos os dias √† meia-noite
  workflow_dispatch:      # Permite rodar manualmente
  push:
    branches:
      - main              # Roda quando houver push na main

jobs:
  generate:
    name: Gerar e publicar anima√ß√£o
    runs-on: ubuntu-latest

    steps:
      - name: Clonar reposit√≥rio
      - uses: actions/checkout@v3

      - name: Gerar a cobrinha
        uses: Platane/snk@v3
        with:
          github_user_name: caiocrdc
          outputs: dist/snake.svg
          snake_color: "#68BBD9"

      - name: Publicar no branch de sa√≠da
        uses: crazy-max/ghaction-github-pages@v4
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
